Car/Car/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from .settings import MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('machine.urls')),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

Car/machine/urls.py
from django.urls import path
from .views import (CarListView, CommentCreateView, update_comment, DeleteCommentView,
                    CarsByColor, CarsByBrand, CarDetailView, user_register,
                    user_login, user_logout, SendEmailView)

urlpatterns = [
    path('', CarListView.as_view(), name="home"),
    path('car/<int:car_id>', CarDetailView.as_view(), name="car_detail"),
    path('car/<int:car_id>/comment/add/', CommentCreateView.as_view(), name="add_comment"),
    path("comment/<int:comment_id>/update/", update_comment, name="update_comment"),
    path("comment/<int:comment_id>/delete/", DeleteCommentView.as_view(), name="delete_comment"),
    path('cars/color/<int:color_id>', CarsByColor.as_view(), name="cars_by_color"),
    path('cars/brand/<int:brand_id>', CarsByBrand.as_view(), name="cars_by_brand"),
    path('register/', user_register, name='register'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),

    path('send-message/', SendEmailView.as_view(), name='send_message_to_email'),

]

Car/machine/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse_lazy


# Create your models here.


class Brand(models.Model):
    title = models.CharField(max_length=100)
    icon = models.ImageField(upload_to="brand/icons", null=True, blank=True)
    created_at = models.DateField()

    def __str__(self):
        return self.title


class Color(models.Model):
    color = models.CharField(max_length=7, default='#FFFFFF')

    def __str__(self):
        return self.color


class Car(models.Model):
    name = models.CharField(max_length=100, verbose_name="Name")
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, verbose_name="Brand")
    color = models.ForeignKey(Color, on_delete=models.CASCADE, verbose_name="Color")
    price = models.PositiveIntegerField(verbose_name="Car price")
    photo = models.ImageField(upload_to="car/photos", null=True, blank=True, verbose_name="Photo")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Machines"
        verbose_name = "Machine"


class Comment(models.Model):
    car = models.ForeignKey("Car", on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Author")
    comment = models.TextField(verbose_name="Comment by author")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.author} - {self.car}"

    def get_absolute_url(self):
        return reverse_lazy('car_detail', kwargs={"car_id": self.car.id})

    class Meta:
        verbose_name = "Comment"
        verbose_name_plural = "Comments"
        ordering = ["-created_at"]

Car/machine/forms.py
from django import forms
from .models import Comment
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']
        widgets = {
            "comment": forms.Textarea(attrs={"class": "form-control", "rows": 3}),
        }


class RegisterForm(UserCreationForm):
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        "class": "form-control form-control-lg",
        "id": "form3Example4cg"
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        "class": "form-control form-control-lg",
        "id": "form3Example4cdg"
    }))

    class Meta:
        model = User
        fields = ('username', 'email')
        widgets = {
            "username": forms.TextInput(attrs={
                "class": "form-control form-control-lg",
                "id": "form3Example1cg"
            }),
            "email": forms.EmailInput(attrs={
                "class": "form-control form-control-lg",
                "id": "form3Example3cg"
            })
        }


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={
        "class": "form-control",
        "id": "form2Example11"
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        "class": "form-control",
        "id": "form2Example22"
    }))


class SendEmail(forms.Form):
    subject = forms.CharField(max_length=250, widget=forms.TextInput(attrs={
        "class": "form-control"
    }))
    message = forms.CharField(widget=forms.Textarea(attrs={
        "class": "form-control",
        "rows": 3
    }))

Car/machine/views.py
import time

from django.contrib.auth import login, authenticate, logout
from django.http import HttpRequest, HttpResponse
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.models import User
from django.conf import settings
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView


from .models import Brand, Color, Car, Comment
from .forms import CommentForm, RegisterForm, LoginForm, SendEmail


# Create your views here.


class CarListView(ListView):
    model = Car
    # template_name = "index.html"
    context_object_name = "cars"
    extra_context = {
        "title": "Asosiy sahifa"
    }

    # def get_context_data(self, *, object_list=None, **kwargs):
    #     context = super().get_context_data()
    #     context["my_brands"] = Brand.objects.all()
    #     return context

# def home(request:HttpRequest):
#     # brands = Brand.objects.all()
#     # colors = Color.objects.all()
#     cars = Car.objects.all()
#     context = {
#         # "brands": brands,
#         # "colors": colors,
#         "cars": cars
#     }
#     return render(request, 'index.html', context)

# ---------------------------------------CRUD------------------------------------


class CarDetailView(DetailView):
    model = Car
    context_object_name = "car"
    pk_url_kwarg = "car_id"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["comments"] = Comment.objects.all()
        # context["comments"] = Comment.objects.filter(car=self.object)
        # context["form"] = CommentForm()
        return context


def car_detail(request, car_id):
    car = get_object_or_404(Car, pk=car_id)
    comments = car.comments.all()
    form = CommentForm()
    context = {
        "car": car,
        "comments": comments,
        "form": form
    }
    return render(request, "car_detail.html", context)


class CommentCreateView(CreateView):
    model = Comment
    fields = ['comment']
    template_name = "add_comment.html"

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.car = Car.objects.get(id=self.kwargs['car_id'])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('car_detail', kwargs={'car_id': self.object.car.id})





def add_comment(request, car_id):
    car = get_object_or_404(Car, pk=car_id)
    if request.method == 'POST':
        if not request.user.is_authenticated:
            messages.error(request, "To add a comment, please register!")
            return redirect("login")

        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.car = car
            comment.save()
            messages.success(request, "Comment added successfully! 👌")
            return redirect("car_detail", car_id=car.id)
        else:
            messages.error(request, "Error adding comment 😞")
    else:
        form = CommentForm()

    return render(request, "add_comment.html", context={"form": form})


def update_comment(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)

    if comment.username != request.user.username:
        messages.error(request, "You can only update your own comments!")
        return redirect("car_detail", car_id=comment.car.id)

    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            messages.success(request, "Update comment ✏")
            return redirect("car_detail", car_id=comment.car.id)
        else:
            messages.error(request, "Error update 🙃🙃🙃")
    else:
        form = CommentForm(instance=comment)

    return render(request, "update_comment.html", context={"form": form, "comment": comment})


class DeleteCommentView(DeleteView):
    model = Comment
    pk_url_kwarg = "comment_id"
    # template_name = "confirm_delete.html"
    context_object_name = "car"
    success_url = reverse_lazy('home')



def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)

    if not request.user.is_authenticated:
        messages.error(request, "To delete comments, please login!")
        return redirect("login")

    if comment.username != request.user.username:
        messages.error(request, "You can only delete your own comments!")
        return redirect("car_detail", car_id=comment.car.id)

    car_id = comment.car.id
    comment.delete()
    messages.success(request, "Success deleted! 🗑")
    return redirect("car_detail", car_id=car_id)


# ---------------------------------------FILTER------------------------------------

class CarsByColor(CarListView):
    def get_queryset(self):
        return Car.objects.filter(color_id=self.kwargs.get("color_id"))


def cars_by_color(request, color_id):
    color = get_object_or_404(Color, pk=color_id)
    cars = Car.objects.filter(color=color)
    context = {
        "color": color,
        "cars": cars
    }
    return render(request, "filter_detail.html", context)


class CarsByBrand(CarListView):
    def get_queryset(self):
        return Car.objects.filter(brand_id=self.kwargs.get("brand_id"))


def cars_by_brand(request, brand_id):
    brand = get_object_or_404(Brand, pk=brand_id)
    cars = Car.objects.filter(brand=brand)
    context = {
        "brand": brand,
        "cars": cars
    }
    return render(request, "filter_detail.html", context)


# ---------------------------------------AUTH------------------------------------

def user_register(request):
    if request.method == 'POST':
        form = RegisterForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            messages.success(request, "Registration successful! 🥳\n"
                                      "Please enter your username and password to log in!")
            return redirect("login")
        else:
            messages.error(request, "Error during registration! 😞")
    else:
        form = RegisterForm()

    context = {
        "form": form
    }
    return render(request, "auth/register.html", context)


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            messages.success(request, f"Logged in successfully! {user.username} 😊")
            return redirect("home")
        else:
            messages.error(request, "Invalid login credentials! 😞")
    else:
        form = LoginForm()

    context = {
        "form": form
    }
    return render(request, "auth/login.html", context)


def user_logout(request):
    logout(request)
    messages.warning(request, "You have been logged out of your account! ☹")
    return redirect("login")


# ----------------------------------------SEND EMAIL--------------------------------------

class SendEmailView(View):
    def post(self, request):
        form = SendEmail(data=request.POST)
        if form.is_valid():
            subject = form.cleaned_data.get("subject")
            message = form.cleaned_data.get("message")
            for user in User.objects.all():
                mail = send_mail(
                    subject=subject,
                    message=message,
                    from_email=settings.EMAIL_HOST_USER,
                    recipient_list=[user.email]
                )
                time.sleep(0.5)
                print(mail, "----------------------------")
        messages.success(request, "Sending news!!!")
        return redirect("home")

    def get(self, request):
        form = SendEmail()
        context = {
            "form": form
        }
        return render(request, "send_mail.html", context)


# def send_message_to_email(request):
#     if request.method == 'POST':
#         form = SendEmail(data=request.POST)
#         if form.is_valid():
#             subject = form.cleaned_data.get("subject")
#             message = form.cleaned_data.get("message")
#             for user in User.objects.all():
#                 mail = send_mail(
#                     subject=subject,
#                     message=message,
#                     from_email=settings.EMAIL_HOST_USER,
#                     recipient_list=[user.email]
#                 )
#                 time.sleep(0.5)
#                 print(mail, "----------------------------")
#         messages.success(request, "Sending news!!!")
#         return redirect("home")
#     else:
#         form = SendEmail()
#     context = {
#         "form": form
#     }
#     return render(request, "send_mail.html", context)

Car/machine/templates/machine/car_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                {% if car.photo %}
                    <img src="{{ car.photo.url }}" class="card-img-top" alt="{{ car.name }}">
                {% endif %}
                <div class="card-body">
                    <h2 class="card-title">{{ car.name }}</h2>
                    <p class="card-text"><strong>Brand:</strong> {{ car.brand }}</p>
                    <p class="card-text"><strong>Color:</strong> {{ car.color }}</p>
                    <p class="card-text"><strong>Price:</strong> ${{ car.price }}</p>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="card p-3">
                <h5>Add a comment:</h5>
                <form method="POST" action="{% url 'add_comment' car.id %}">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="id_comment" class="form-label">Your comment:</label>
                        <textarea name="comment" id="id_comment" class="form-control" rows="3"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Add Comment</button>
                </form>
            </div>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-12">
            <h3>Comments:</h3>
            {% for comment in car.comments.all %}
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">{{ comment.author }}</h5>
                        <p class="card-text">{{ comment.comment }}</p>
                        <small class="text-muted">{{ comment.created_at }}</small>

                        {% if request.user.is_authenticated and request.user == comment.author %}
                        <div class="mt-2">
                            <a href="{% url 'update_comment' comment.id %}" class="btn btn-sm btn-warning">Edit</a>
                            <a href="{% url 'delete_comment' comment.id %}" class="btn btn-sm btn-danger">Delete</a>
                        </div>
                        {% endif %}

                    </div>
                </div>
            {% empty %}
                <p>No comments yet.</p>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

Car/machine/templates/machine/car_list.html
{% extends 'base.html' %}
{% load custom_tags %}
{% block content %}

<!--{{ my_brands }}-->

<div class="container mt-4">
    <h2 class="text-center">Brands</h2>
    <div class="d-flex justify-content-around flex-wrap">
        {% get_brands as brands %}
        {% for brand in brands %}
        <div>
            <a href="{% url 'cars_by_brand' brand.id %}" class="btn btn-outline-primary">
                {{ brand.title }}
            </a>
        </div>
        {% endfor %}
    </div>
</div>

<hr>

<div class="container">
    <h2 class="text-center">Colors</h2>
    <div class="d-flex justify-content-around flex-wrap">
        {% get_colors as colors %}
        {% for color in colors %}
        <div>
            <a href="{% url 'cars_by_color' color.id %}" class="btn btn-outline-secondary" style="background-color: {{ color.color }};">
                {{ color.color }}
            </a>
        </div>
        {% endfor %}
    </div>
</div>

<hr>

<div class="container py-5">
    <h2 class="text-center">Available Cars</h2>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for car in object_list %}
        <div class="col">
            <div class="card h-100">
                {% if car.photo %}
                <img src="{{ car.photo.url }}" class="card-img-top" alt="{{ car.name }}">
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">
                        <a href="{% url 'car_detail' car.id %}">{{ car.name }}</a>
                    </h5>
                    <p class="card-text"><strong>Brand:</strong> {{ car.brand }}</p>
                    <p class="card-text"><strong>Color:</strong> {{ car.color }}</p>
                    <p class="card-text"><strong>Price:</strong> ${{ car.price }}</p>
                </div>
                <div class="card-footer">
                    <a href="{% url 'car_detail' car.id %}" class="btn btn-primary">View Details</a>
                </div>
            </div>
        </div>
        {% empty %}
        <p class="text-center">No cars available.</p>
        {% endfor %}
    </div>
</div>

{% endblock content %}

Car/machine/templates/machine/comment_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h3>Confirm delete </h3>
<form method="post">
    {% csrf_token %}
    <button type="submit"> Yes </button>
</form>
<a href="{% url 'car_detail' car.pk %}"></a>
</body>
</html>